# Check if config is valid after changes: circleci config validate
version: 2.1
orbs:
  snyk: snyk/snyk@0.0.10
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/ex4-cookies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: install npm packages
          command: npm install
      - save_cache:
          key: v2-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: medium
  test:
    working_directory: ~/ex4-cookies
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: 
          name: run tests
          command: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build