# Check if config is valid after changes: circleci config validate
version: 2.1
jobs:
  build:
    working_directory: ~/ex4-cookies
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: app-{{ arch }}-{{ checksum "package.json" }}
      - run: 
          name: install npm packages
          command: npm install
      - save_cache:
          key: app-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ~/ex4-cookies/node_modules
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: medimum
  test:
    working_directory: ~/ex4-cookies
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: 
          name: run tests
          command: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
orbs:
  snyk: snyk/snyk@0.0.3 